[project]
name = "12thmanv2"
version = "0.1.0"
description = "12thManV2 using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.102.0,<1.0.0"
]

[project.scripts]
12thmanv2 = "12thmanv2.main:run"
run_crew = "12thmanv2.main:run"
train = "12thmanv2.main:train"
replay = "12thmanv2.main:replay"
test = "12thmanv2.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
